### ISSUE TITLE
Cannot load or save to drives other than C:

### ISSUE THREAD

**Issue by jsmith04** [TeledyneLeCroy/SignalIntegrity#47]
The following error shows when trying to load a touchstone file from my Y: drive which is mapped to a network folder.  This error occurs when trying to load/save a project or load touchstone files for the s parameter viewer.

The same files load fine when moved to my C: drive.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\users\[user]\appdata\local\continuum\anaconda2\lib\lib-tk\Tkinter.py", line 1547, in __call__
    return self.func(*args)
  File "c:\users\[user]\appdata\local\continuum\anaconda2\lib\site-packages\SignalIntegrity\App\MenuSystemHelpers.py", line 138, in Execute
    return self.command()
  File "c:\users\[user]\appdata\local\continuum\anaconda2\lib\site-packages\SignalIntegrity\App\SignalIntegrityApp.py", line 791, in onSParameterViewer
    fileparts=FileParts(filename)
  File "c:\users\[user]\appdata\local\continuum\anaconda2\lib\site-packages\SignalIntegrity\App\Files.py", line 38, in __init__
    filename=ConvertFileNameToRelativePath(filename)
  File "c:\users\[user]\appdata\local\continuum\anaconda2\lib\site-packages\SignalIntegrity\App\Files.py", line 24, in ConvertFileNameToRelativePath
    filename=os.path.relpath(filename,os.getcwd())
  File "c:\users\[user]\appdata\local\continuum\anaconda2\lib\ntpath.py", line 529, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive Y:, start on drive C:
```

**Comment by PetePupalaikis** [comment]
This is an error that I'm aware of.  The problem is that everything is referenced as relative paths from your project directory.  I mostly work on Linux where everything can be accessed with a relative path.  On windows, there is no relative path between two drives with different letters.

I need to think of how to deal with that.  For now, the workaround is to keep all referenced files in a project and the project file such that there is a relative path between them.
